### ISSUE TITLE
Fix Travis-CI automatic deployment 

### ISSUE THREAD

**Issue by MKLau** [ProvTools/provtools.github.io#1]
Currently, there's an issue with Travis' server not recognizing the rsa_key.

**Comment by tfjmp** [comment]
You should use the token I showed you the other day. That is more easy to setup.

**Comment by MKLau** [comment]
Yeah, I had it setup with the github OA token, but I had used someone's yml as a template that was creating a gh-pages branch, while organization pages only publish from master. I'll take another look today.

**Comment by MKLau** [comment]
Ah, here we go: https://docs.travis-ci.com/user/deployment/pages/
